global:
  redis:
    managed: false
  mongodb:
    managed: false
  postgresql:
    managed: false
  database:
    managed: false

nodebb:
  database: mongo
  admin:
    username: "nevex"
    email: "nevex.net@proton.me"
    password: "XXzJdPY5FI21y9lN9d"

mongodb:
  auth:
    host: mongodb-psmdb-db-mongos.nodebb.svc.cluster.local
    port: 27017
    username: nodebb
    password: S0FQWWNnOHl2dWFVUzVsbjNF
    database: nodebb

imagePullSecrets:
  - name: dockerconfigjson-github-com
